### ISSUE TITLE
Too few arguments to function Nwidart\Modules\Repository::enabled()

### ISSUE THREAD

**Issue by viktormaar** [balping/asset-bundler#1]
When trying to run `php artisan module:bundle-assets`, I get the following error:

> Type error: Too few arguments to function Nwidart\Modules\Repository::enabled(), 0 passed in [...]/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 221 and exactly 1 expected   

I can get it working by using **Module::allEnabled()** instead. Tho' I use Laravel 5.5.36

**Comment by balping** [comment]
In v0.0.3 I fixed this. `enabled` was renamed to `allEnabled` in laravel modules 3.0 which supports only Laravel 5.6. But it seams that you have somehow laravel modules 3 installed in laravel 5.5, which is strange, because their composer.json explicitly requires 5.6*. So ensure that you install laravel modules 2.7 or upgrade to L5.6 and use asset-bundler v0.0.3

**Comment by viktormaar** [comment]
You are right. The problem was with the confused versions, and not with the Asset-bundler. A simple commad of `composer require nwidart/laravel-modules` without version specification automatically installs Modules v3 on a Laravel 5.5.
Solved with updating Laravel to 5.6. Thank you for reply.
